#!/bin/sh

if ! command -v ronn; then
	echo '
Please install "ronn". This tool is needed to convert markdown to man pages.
This tool is needed to convert files under docs/usage into man pages for the
installation.

https://github.com/rtomayko/ronn
'
	exit 1
fi

for i in "$(dirname "${0}")"/../docs/usage/distrobox-*; do
	ronn --manual=Distrobox --name="$(basename "${i}" | cut -d'.' -f1).1" --organization=Distrobox "${i}" -o "$(dirname "${0}")"/man1/
	mv "$(dirname "${0}")/man1/$(basename "${i}" | cut -d'.' -f1)" "$(dirname "${0}")/man1/$(basename "${i}" | sed 's|md|1|g')"
	rm -f "$(dirname "${0}")"/man1/*.html
done
