#!/usr/bin/env -i sh 
# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the distrobox project:
#    https://github.com/89luca89/distrobox
#
# Copyright (C) 2021 distrobox contributors
#
# distrobox is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# distrobox is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with distrobox; if not, see <http://www.gnu.org/licenses/>.
printf "RUN create-command"

set -o nounset

# shellcheck disable=SC1090 disable=SC1091
. "$(dirname "${0}")/../lib/create-command"

printf "create_command: Test insufficient parameters... "
# Missing 1 parameter
if ! generate_create_command \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	0 \
	0 2> /dev/null; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test too many parameters... "
# Exceeding 1 parameter
if ! generate_create_command \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	0 \
	0 2> /dev/null; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test right number of parameters... "
if generate_create_command \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	"" \
	0 \
	0 > /dev/null; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test basic container create... "
cmd="$(generate_create_command \
	"alpine:latest" \
	"" \
	"test-container-manager" \
	"" \
	"test-container-name" \
	"" \
	"999" \
	"/home/test-home" \
	"" \
	"test-user" \
	"999" \
	"/tmp/distrobox-entrypoint" \
	"/tmp/distrobox-export" \
	"/tmp/distrobox-host-exec" \
	0 \
	0)"
expected="test-container-manager create
		--hostname \"test-container-name.$(uname -n)\"
		--ipc host
		--name \"test-container-name\"
		--network host
		--privileged
		--security-opt label=disable
		--user root:root
			--pid host
		--label \"manager=distrobox\"
		--env \"SHELL=/bin/bash\"
		--env \"HOME=/home/test-home\"
		--volume /:/run/host:rslave
		--volume /dev:/dev:rslave
		--volume /sys:/sys:rslave
		--volume /tmp:/tmp:rslave
		--volume \"/tmp/distrobox-entrypoint\":/usr/bin/entrypoint:ro
		--volume \"/tmp/distrobox-export\":/usr/bin/distrobox-export:ro
		--volume \"/tmp/distrobox-host-exec\":/usr/bin/distrobox-host-exec:ro
		--volume \"/home/test-home\":\"/home/test-home\":rslave
			--volume /sys/fs/selinux
			--volume /var/log/journal
		--volume /etc/hosts:/etc/hosts:ro
		--volume /etc/localtime:/etc/localtime:ro
		--volume /etc/resolv.conf:/etc/resolv.conf:ro  alpine:latest
		/usr/bin/entrypoint -v --name \"test-user\"
		--user 999
		--group 999
		--home \"/home/test-home\"
		--init \"0\"
		
		-- ''
		"
if [ "${cmd}" = "${expected}" ]; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test container create with init-hooks... "
cmd="$(generate_create_command \
	"alpine:latest" \
	"umount /tmp" \
	"test-container-manager" \
	"" \
	"test-container-name" \
	"" \
	"999" \
	"/home/test-home" \
	"" \
	"test-user" \
	"999" \
	"/tmp/distrobox-entrypoint" \
	"/tmp/distrobox-export" \
	"/tmp/distrobox-host-exec" \
	0 \
	0)"
expected="test-container-manager create
		--hostname \"test-container-name.$(uname -n)\"
		--ipc host
		--name \"test-container-name\"
		--network host
		--privileged
		--security-opt label=disable
		--user root:root
			--pid host
		--label \"manager=distrobox\"
		--env \"SHELL=/bin/bash\"
		--env \"HOME=/home/test-home\"
		--volume /:/run/host:rslave
		--volume /dev:/dev:rslave
		--volume /sys:/sys:rslave
		--volume /tmp:/tmp:rslave
		--volume \"/tmp/distrobox-entrypoint\":/usr/bin/entrypoint:ro
		--volume \"/tmp/distrobox-export\":/usr/bin/distrobox-export:ro
		--volume \"/tmp/distrobox-host-exec\":/usr/bin/distrobox-host-exec:ro
		--volume \"/home/test-home\":\"/home/test-home\":rslave
			--volume /sys/fs/selinux
			--volume /var/log/journal
		--volume /etc/hosts:/etc/hosts:ro
		--volume /etc/localtime:/etc/localtime:ro
		--volume /etc/resolv.conf:/etc/resolv.conf:ro  alpine:latest
		/usr/bin/entrypoint -v --name \"test-user\"
		--user 999
		--group 999
		--home \"/home/test-home\"
		--init \"0\"
		
		-- 'umount /tmp'
		"
if [ "${cmd}" = "${expected}" ]; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test container create with additional flags... "
cmd="$(generate_create_command \
	"alpine:latest" \
	"umount /tmp" \
	"test-container-manager" \
	"--test-flag" \
	"test-container-name" \
	"" \
	"999" \
	"/home/test-home" \
	"" \
	"test-user" \
	"999" \
	"/tmp/distrobox-entrypoint" \
	"/tmp/distrobox-export" \
	"/tmp/distrobox-host-exec" \
	0 \
	0)"
expected="test-container-manager create
		--hostname \"test-container-name.$(uname -n)\"
		--ipc host
		--name \"test-container-name\"
		--network host
		--privileged
		--security-opt label=disable
		--user root:root
			--pid host
		--label \"manager=distrobox\"
		--env \"SHELL=/bin/bash\"
		--env \"HOME=/home/test-home\"
		--volume /:/run/host:rslave
		--volume /dev:/dev:rslave
		--volume /sys:/sys:rslave
		--volume /tmp:/tmp:rslave
		--volume \"/tmp/distrobox-entrypoint\":/usr/bin/entrypoint:ro
		--volume \"/tmp/distrobox-export\":/usr/bin/distrobox-export:ro
		--volume \"/tmp/distrobox-host-exec\":/usr/bin/distrobox-host-exec:ro
		--volume \"/home/test-home\":\"/home/test-home\":rslave
			--volume /sys/fs/selinux
			--volume /var/log/journal
		--volume /etc/hosts:/etc/hosts:ro
		--volume /etc/localtime:/etc/localtime:ro
		--volume /etc/resolv.conf:/etc/resolv.conf:ro --test-flag alpine:latest
		/usr/bin/entrypoint -v --name \"test-user\"
		--user 999
		--group 999
		--home \"/home/test-home\"
		--init \"0\"
		
		-- 'umount /tmp'
		"
if [ "${cmd}" = "${expected}" ]; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test container create with pre-init hooks... "
cmd="$(generate_create_command \
	"alpine:latest" \
	"umount /tmp" \
	"test-container-manager" \
	"--test-flag" \
	"test-container-name" \
	"test pre init hook" \
	"999" \
	"/home/test-home" \
	"" \
	"test-user" \
	"999" \
	"/tmp/distrobox-entrypoint" \
	"/tmp/distrobox-export" \
	"/tmp/distrobox-host-exec" \
	0 \
	0)"
expected="test-container-manager create
		--hostname \"test-container-name.$(uname -n)\"
		--ipc host
		--name \"test-container-name\"
		--network host
		--privileged
		--security-opt label=disable
		--user root:root
			--pid host
		--label \"manager=distrobox\"
		--env \"SHELL=/bin/bash\"
		--env \"HOME=/home/test-home\"
		--volume /:/run/host:rslave
		--volume /dev:/dev:rslave
		--volume /sys:/sys:rslave
		--volume /tmp:/tmp:rslave
		--volume \"/tmp/distrobox-entrypoint\":/usr/bin/entrypoint:ro
		--volume \"/tmp/distrobox-export\":/usr/bin/distrobox-export:ro
		--volume \"/tmp/distrobox-host-exec\":/usr/bin/distrobox-host-exec:ro
		--volume \"/home/test-home\":\"/home/test-home\":rslave
			--volume /sys/fs/selinux
			--volume /var/log/journal
		--volume /etc/hosts:/etc/hosts:ro
		--volume /etc/localtime:/etc/localtime:ro
		--volume /etc/resolv.conf:/etc/resolv.conf:ro --test-flag alpine:latest
		/usr/bin/entrypoint -v --name \"test-user\"
		--user 999
		--group 999
		--home \"/home/test-home\"
		--init \"0\"
		test pre init hook
		-- 'umount /tmp'
		"
if [ "${cmd}" = "${expected}" ]; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test container create with custom home... "
cmd="$(generate_create_command \
	"alpine:latest" \
	"umount /tmp" \
	"test-container-manager" \
	"--test-flag" \
	"test-container-name" \
	"test pre init hook" \
	"999" \
	"/home/test-home" \
	"/home/custom-user-home" \
	"test-user" \
	"999" \
	"/tmp/distrobox-entrypoint" \
	"/tmp/distrobox-export" \
	"/tmp/distrobox-host-exec" \
	0 \
	0)"
expected="test-container-manager create
		--hostname \"test-container-name.$(uname -n)\"
		--ipc host
		--name \"test-container-name\"
		--network host
		--privileged
		--security-opt label=disable
		--user root:root
			--pid host
		--label \"manager=distrobox\"
		--env \"SHELL=/bin/bash\"
		--env \"HOME=/home/test-home\"
		--volume /:/run/host:rslave
		--volume /dev:/dev:rslave
		--volume /sys:/sys:rslave
		--volume /tmp:/tmp:rslave
		--volume \"/tmp/distrobox-entrypoint\":/usr/bin/entrypoint:ro
		--volume \"/tmp/distrobox-export\":/usr/bin/distrobox-export:ro
		--volume \"/tmp/distrobox-host-exec\":/usr/bin/distrobox-host-exec:ro
		--volume \"/home/test-home\":\"/home/test-home\":rslave
			--volume /sys/fs/selinux
			--volume /var/log/journal
			--env \"HOME=/home/custom-user-home\"
			--env \"DISTROBOX_HOST_HOME=/home/test-home\"
			--volume \"/home/custom-user-home:/home/custom-user-home:rslave\"
		--volume /etc/hosts:/etc/hosts:ro
		--volume /etc/localtime:/etc/localtime:ro
		--volume /etc/resolv.conf:/etc/resolv.conf:ro --test-flag alpine:latest
		/usr/bin/entrypoint -v --name \"test-user\"
		--user 999
		--group 999
		--home \"/home/custom-user-home\"
		--init \"0\"
		test pre init hook
		-- 'umount /tmp'
		"
if [ "${cmd}" = "${expected}" ]; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test container create with systemd... "
cmd="$(generate_create_command \
	"alpine:latest" \
	"umount /tmp" \
	"test-container-manager" \
	"--test-flag" \
	"test-container-name" \
	"test pre init hook" \
	"999" \
	"/home/test-home" \
	"/home/custom-user-home" \
	"test-user" \
	"999" \
	"/tmp/distrobox-entrypoint" \
	"/tmp/distrobox-export" \
	"/tmp/distrobox-host-exec" \
	1 \
	0)"
expected="test-container-manager create
		--hostname \"test-container-name.$(uname -n)\"
		--ipc host
		--name \"test-container-name\"
		--network host
		--privileged
		--security-opt label=disable
		--user root:root
		--label \"manager=distrobox\"
		--env \"SHELL=/bin/bash\"
		--env \"HOME=/home/test-home\"
		--volume /:/run/host:rslave
		--volume /dev:/dev:rslave
		--volume /sys:/sys:rslave
		--volume /tmp:/tmp:rslave
		--volume \"/tmp/distrobox-entrypoint\":/usr/bin/entrypoint:ro
		--volume \"/tmp/distrobox-export\":/usr/bin/distrobox-export:ro
		--volume \"/tmp/distrobox-host-exec\":/usr/bin/distrobox-host-exec:ro
		--volume \"/home/test-home\":\"/home/test-home\":rslave
			--volume /sys/fs/selinux
			--volume /var/log/journal
			--env \"HOME=/home/custom-user-home\"
			--env \"DISTROBOX_HOST_HOME=/home/test-home\"
			--volume \"/home/custom-user-home:/home/custom-user-home:rslave\"
		--volume /etc/hosts:/etc/hosts:ro
		--volume /etc/localtime:/etc/localtime:ro
		--volume /etc/resolv.conf:/etc/resolv.conf:ro --test-flag alpine:latest
		/usr/bin/entrypoint -v --name \"test-user\"
		--user 999
		--group 999
		--home \"/home/custom-user-home\"
		--init \"1\"
		test pre init hook
		-- 'umount /tmp'
		"
if [ "${cmd}" = "${expected}" ]; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test container create with systemd and podman... "
cmd="$(generate_create_command \
	"alpine:latest" \
	"umount /tmp" \
	"podman" \
	"--test-flag" \
	"test-container-name" \
	"test pre init hook" \
	"999" \
	"/home/test-home" \
	"/home/custom-user-home" \
	"test-user" \
	"999" \
	"/tmp/distrobox-entrypoint" \
	"/tmp/distrobox-export" \
	"/tmp/distrobox-host-exec" \
	1 \
	0)"
expected="podman create
		--hostname \"test-container-name.$(uname -n)\"
		--ipc host
		--name \"test-container-name\"
		--network host
		--privileged
		--security-opt label=disable
		--user root:root
		--label \"manager=distrobox\"
		--env \"SHELL=/bin/bash\"
		--env \"HOME=/home/test-home\"
		--volume /:/run/host:rslave
		--volume /dev:/dev:rslave
		--volume /sys:/sys:rslave
		--volume /tmp:/tmp:rslave
		--volume \"/tmp/distrobox-entrypoint\":/usr/bin/entrypoint:ro
		--volume \"/tmp/distrobox-export\":/usr/bin/distrobox-export:ro
		--volume \"/tmp/distrobox-host-exec\":/usr/bin/distrobox-host-exec:ro
		--volume \"/home/test-home\":\"/home/test-home\":rslave
			--volume /sys/fs/selinux
			--volume /var/log/journal
			--env \"HOME=/home/custom-user-home\"
			--env \"DISTROBOX_HOST_HOME=/home/test-home\"
			--volume \"/home/custom-user-home:/home/custom-user-home:rslave\"
		--volume /etc/hosts:/etc/hosts:ro
		--volume /etc/localtime:/etc/localtime:ro
		--volume /etc/resolv.conf:/etc/resolv.conf:ro
			--ulimit host
			--annotation run.oci.keep_original_groups=1
			--mount type=devpts,destination=/dev/pts
				--systemd=always
				--userns keep-id --test-flag alpine:latest
		/usr/bin/entrypoint -v --name \"test-user\"
		--user 999
		--group 999
		--home \"/home/custom-user-home\"
		--init \"1\"
		test pre init hook
		-- 'umount /tmp'
		"
if [ "${cmd}" = "${expected}" ]; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi

printf "create_command: Test container create with systemd, podman and rootful... "
cmd="$(generate_create_command \
	"alpine:latest" \
	"umount /tmp" \
	"podman" \
	"--test-flag" \
	"test-container-name" \
	"test pre init hook" \
	"999" \
	"/home/test-home" \
	"/home/custom-user-home" \
	"test-user" \
	"999" \
	"/tmp/distrobox-entrypoint" \
	"/tmp/distrobox-export" \
	"/tmp/distrobox-host-exec" \
	1 \
	1)"
expected="podman create
		--hostname \"test-container-name.$(uname -n)\"
		--ipc host
		--name \"test-container-name\"
		--network host
		--privileged
		--security-opt label=disable
		--user root:root
		--label \"manager=distrobox\"
		--env \"SHELL=/bin/bash\"
		--env \"HOME=/home/test-home\"
		--volume /:/run/host:rslave
		--volume /dev:/dev:rslave
		--volume /sys:/sys:rslave
		--volume /tmp:/tmp:rslave
		--volume \"/tmp/distrobox-entrypoint\":/usr/bin/entrypoint:ro
		--volume \"/tmp/distrobox-export\":/usr/bin/distrobox-export:ro
		--volume \"/tmp/distrobox-host-exec\":/usr/bin/distrobox-host-exec:ro
		--volume \"/home/test-home\":\"/home/test-home\":rslave
			--volume /sys/fs/selinux
			--volume /var/log/journal
			--env \"HOME=/home/custom-user-home\"
			--env \"DISTROBOX_HOST_HOME=/home/test-home\"
			--volume \"/home/custom-user-home:/home/custom-user-home:rslave\"
		--volume /etc/hosts:/etc/hosts:ro
		--volume /etc/localtime:/etc/localtime:ro
		--volume /etc/resolv.conf:/etc/resolv.conf:ro
			--ulimit host
			--annotation run.oci.keep_original_groups=1
			--mount type=devpts,destination=/dev/pts
				--systemd=always --test-flag alpine:latest
		/usr/bin/entrypoint -v --name \"test-user\"
		--user 999
		--group 999
		--home \"/home/custom-user-home\"
		--init \"1\"
		test pre init hook
		-- 'umount /tmp'
		"
if [ "${cmd}" = "${expected}" ]; then
	printf "PASS\n"
else
	printf "FAIL\n"
	diff <(echo "$cmd") <(echo "$expected")
	exit 1
fi
