#!/usr/bin/env -S -i sh
# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the distrobox project:
#    https://github.com/89luca89/distrobox
#
# Copyright (C) 2021 distrobox contributors
#
# distrobox is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# distrobox is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with distrobox; if not, see <http://www.gnu.org/licenses/>.
printf "RUN clone-command\n"

set -o nounset

# shellcheck disable=SC1090 disable=SC1091
. "$(dirname "${0}")/../lib/create-command"

printf "clone_command: Test insufficient parameters... "
# Missing 1 parameter
if ! clone_container 2> /dev/null; then
	printf "PASS\n"
else
	printf "FAIL\n"
	exit 1
fi

printf "clone_command: Test too many parameters... "
# Exceeding 1 parameter
if ! clone_container \
	"a" \
	"b" \
	"c" 2> /dev/null; then
	printf "PASS\n"
else
	printf "FAIL\n"
	exit 1
fi
