.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-RM\.1" "" "January 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-rm\.1\fR
.SS "Remove containers"
distrobox\-rm delete one of the available distroboxes\.
.P
Usage:
.IP "" 4
.nf
distrobox\-rm \-\-name container\-name [\-\-force]
distrobox\-rm container\-name [\-f]
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-name/\-n:		name for the distrobox
\-\-force/\-f:		force deletion
\-\-help/\-h:		show this message
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0

