.\
.\"
.\" Define V font for inline verbatim, using C font in formats
.\" that render this, and otherwise B font.
.ie "\f[CB]x\f[]"x" \{\
. ftr V B
. ftr VI BI
. ftr VB B
. ftr VBI BI
.\}
.el \{\
. ftr V CR
. ftr VI CI
. ftr VB CB
. ftr VBI CBI
.\}
.TH "DISTROBOX-INIT" "1" "Nov 2022" "Distrobox" "User Manual"
.hy
.SH NAME
.IP
.nf
\f[C]
distrobox-init
\f[R]
.fi
.SH DESCRIPTION
.PP
\f[B]Init the distrobox (not to be launched manually)\f[R]
.PP
distrobox-init is the entrypoint of a created distrobox.
Note that this HAS to run from inside a distrobox, will not work if you
run it from your host.
.PP
\f[B]This is not intended to be used manually, but instead used by
distrobox-create to set up the container\[cq]s entrypoint.\f[R]
.PP
distrobox-init will take care of installing missing dependencies (eg.
sudo), set up the user and groups, mount directories from the host to
ensure the tight integration.
.SH SYNOPSIS
.PP
\f[B]distrobox-init\f[R]
.IP
.nf
\f[C]
--name/-n:      user name
--user/-u:      uid of the user
--group/-g:     gid of the user
--home/-d:      path/to/home of the user
--help/-h:      show this message
--init/-I:      whether to use or not init
--pre-init-hooks:   commands to execute prior to init
--upgrade/-U:       run init in upgrade mode
--verbose/-v:       show more verbosity
--version/-V:       show version
--:         end arguments execute the rest as command to execute during init
\f[R]
.fi
.SH EXAMPLES
.IP
.nf
\f[C]
distrobox-init --name test-user --user 1000 --group 1000 --home /home/test-user
distrobox-init --upgrade
\f[R]
.fi
