.\
.\"
.\" Define V font for inline verbatim, using C font in formats
.\" that render this, and otherwise B font.
.ie "\f[CB]x\f[]"x" \{\
. ftr V B
. ftr VI BI
. ftr VB B
. ftr VBI BI
.\}
.el \{\
. ftr V CR
. ftr VI CI
. ftr VB CB
. ftr VBI CBI
.\}
.TH "DISTROBOX-UPGRADE" "1" "Jun 2023" "Distrobox" "User Manual"
.hy
.SH NAME
.IP
.nf
\f[C]
distrobox-upgrade
\f[R]
.fi
.SH DESCRIPTION
.PP
distrobox-upgrade will enter the specified list of containers and will
perform an upgrade using the container\[cq]s package manager.
.SH SYNOPSIS
.PP
\f[B]distrobox upgrade\f[R]
.IP
.nf
\f[C]
--help/-h:      show this message
--all/-a:       perform for all distroboxes
--root/-r:      launch podman/docker with root privileges. Note that if you need root this is the preferred
            way over \[dq]sudo distrobox\[dq] (note: if using a program other than \[aq]sudo\[aq] for root privileges is necessary,
            specify it through the DBX_SUDO_PROGRAM env variable, or \[aq]distrobox_sudo_program\[aq] config variable)
--verbose/-v:       show more verbosity
--version/-V:       show version
\f[R]
.fi
.SH EXAMPLES
.PP
Upgrade all distroboxes
.IP
.nf
\f[C]
distrobox-upgrade --all
\f[R]
.fi
.PP
Upgrade a specific distrobox
.IP
.nf
\f[C]
distrobox-upgrade alpine-linux 
\f[R]
.fi
.PP
Upgrade a list of distroboxes
.IP
.nf
\f[C]
distrobox-upgrade alpine-linux ubuntu22 my-distrobox123
\f[R]
.fi
.PP
\f[B]Automatically update all distro\f[R]
.PP
You can create a systemd service to perform distrobox-upgrade
automatically, this example shows how to run it daily:
.PP
\[ti]/.config/systemd/user/distrobox-upgrade.service
.IP
.nf
\f[C]
[Unit]
Description=distrobox-upgrade Automatic Update

[Service]
Type=simple
ExecStart=distrobox-upgrade --all
StandardOutput=null
\f[R]
.fi
.PP
\[ti]/.config/systemd/user/distrobox-upgrade.timer
.IP
.nf
\f[C]
[Unit]
Description=distrobox-upgrade Automatic Update Trigger

[Timer]
OnBootSec=1h
OnUnitInactiveSec=1d

[Install]
WantedBy=timers.target
\f[R]
.fi
.PP
Then simply do a
\f[V]systemctl --user daemon reload && systemctl --user enable --now distrobox-upgrade.timer\f[R]
