.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-ENTER\.1" "" "January 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-enter\.1\fR
.SS "Enter the distrobox"
distrobox\-enter takes care of entering the container with the name specified\. Default command executed is your SHELL, but you can specify different shells or entire commands to execute\. If using it inside a script, an application, or a service, you can specify the \-\-headless mode to disable tty and interactivity\.
.P
Usage:
.IP "" 4
.nf
distrobox\-enter \-\-name fedora\-toolbox\-35 \-\- bash \-l
distrobox\-enter my\-alpine\-container \-\- sh \-l
distrobox\-enter \-\-additional\-flags "\-\-preserve\-fds" \-\-name test \-\- bash \-l
distrobox\-enter \-\-additional\-flags "\-\-env MY_VAR=value" \-\-name test \-\- bash \-l
MY_VAR=value distrobox\-enter \-\-additional\-flags "\-\-preserve\-fds" \-\-name test \-\- bash \-l
.fi
.IP "" 0
.P
Supported environment variables:
.IP "" 4
.nf
DBX_CONTAINER_NAME
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-name/\-n:		name for the distrobox						default: fedora\-toolbox\-35
\-\-/\-e:			end arguments execute the rest as command to execute at login	default: bash \-l
\-\-headless/\-H:		do not instantiate a tty
\-\-additional\-flags/\-a:	additional flags to pass to the container manager command
\-\-help/\-h:		show this message
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0
.P
This is used to enter the distrobox itself\. Personally, I just create multiple profiles in my \fBgnome\-terminal\fR to have multiple distros accessible\.
