.\
.\"
.TH "DISTROBOX\-LIST" "1" "Nov 2025" "Distrobox" "User Manual"
.SH NAME
.IP
.EX
distrobox list
distrobox\-list
.EE
.SH DESCRIPTION
distrobox\-list lists available distroboxes.
It detects them and lists them separately from the rest of normal
containers.
.SH SYNOPSIS
\f[B]distrobox list\f[R]
.IP
.EX
\-\-help/\-h:      show this message
\-\-no\-color:     disable color formatting
\-\-root/\-r:      launch podman/docker/lilipod with root privileges. Note that if you need root this is the preferred
            way over \[dq]sudo distrobox\[dq] (note: if using a program other than \[aq]sudo\[aq] for root privileges is necessary,
            specify it through the DBX_SUDO_PROGRAM env variable, or \[aq]distrobox_sudo_program\[aq] config variable)
\-\-verbose/\-v:       show more verbosity
\-\-version/\-V:       show version
.EE
.SH EXAMPLES
.IP
.EX
distrobox\-list
.EE
.PP
You can also use environment variables to specify container manager
.IP
.EX
DBX_CONTAINER_MANAGER=\[dq]docker\[dq] distrobox\-list
.EE
.SH ENVIRONMENT VARIABLES
.IP
.EX
DBX_CONTAINER_MANAGER
DBX_SUDO_PROGRAM
.EE
[IMAGE: \c
.UR https://user-images.githubusercontent.com/598882/147831082-24b5bc2e-b47e-49ac-9b1a-a209478c9705.png
image
.UE \c
]
image
