.\
.\"
.TH "DISTROBOX\-GENERATE\-ENTRY" "1" "Oct 2025" "Distrobox" "User Manual"
.SH NAME
.IP
.EX
distrobox generate\-entry
.EE
.SH DESCRIPTION
distrobox\-generate\-entry will create a desktop icon for one of the
available distroboxes.
This will be then deleted when you remove the matching distrobox.
.SH SYNOPSIS
\f[B]distrobox generate\-entry\f[R]
.IP
.EX
\-\-help/\-h:      show this message
\-\-all/\-a:       perform for all distroboxes
\-\-delete/\-d:        delete the entry
\-\-icon/\-i:      specify a custom icon [/path/to/icon] (default auto)
\-\-root/\-r:      perform on rootful distroboxes
\-\-verbose/\-v:       show more verbosity
\-\-version/\-V:       show version
.EE
.SH EXAMPLES
Generate an entry for a container
.IP
.EX
distrobox generate\-entry my\-container\-name
.EE
.PP
Specify a custom icon for the entry
.IP
.EX
distrobox generate\-entry my\-container\-name \-\-icon /path/to/icon.png
.EE
.PP
Generate an entry for all distroboxes
.IP
.EX
distrobox generate\-entry \-\-all
.EE
.PP
Delete an entry
.IP
.EX
distrobox generate\-entry container\-name \-\-delete
.EE
