.\
.\"
.\" Define V font for inline verbatim, using C font in formats
.\" that render this, and otherwise B font.
.ie "\f[CB]x\f[]"x" \{\
. ftr V B
. ftr VI BI
. ftr VB B
. ftr VBI BI
.\}
.el \{\
. ftr V CR
. ftr VI CI
. ftr VB CB
. ftr VBI CBI
.\}
.TH "DISTROBOX-GENERATE-ENTRY" "1" "Nov 2022" "Distrobox" "User Manual"
.hy
.SH NAME
.IP
.nf
\f[C]
distrobox generate-entry
\f[R]
.fi
.SH DESCRIPTION
.PP
distrobox-generate-entry will create a desktop icon for one of the
available distroboxes.
This will be then deleted when you remove the matching distrobox.
.SH SYNOPSIS
.PP
\f[B]distrobox generate-entry\f[R]
.IP
.nf
\f[C]
    --help/-h:            show this message
    --all/-a:              perform for all distroboxes
    --delete/-d:            delete the entry
    --icon/-i:            specify a custom icon [/path/to/icon] (default auto)
    --verbose/-v:          show more verbosity
    --version/-V:          show version
\f[R]
.fi
.SH EXAMPLES
.IP
.nf
\f[C]
distrobox-generate-entry container-name [--delete] [--icon [auto,/path/to/icon]]
\f[R]
.fi
