.TH DISTROBOX-EXPORT "1" "January 2022" "distrobox" "General Commands Manual"
.SH NAME
distrobox-export
.SH DESCRIPTION
distrobox\-export takes care of exporting an app a binary or a service from the container
to the host.
.PP
The exported app will be easily available in your normal launcher and it will
automatically be launched from the container it is exported from.
.PP
The exported services will be available in the host's user's systemd session, so
systemctl \fB\-\-user\fR status exported_service_name
.PP
will show the status of the service exported.
.PP
The exported binaries will be exported in the "\-\-export\-path" of choice as a wrapper
script that acts naturally both on the host and in the container.
Note that "\-\-export\-path" is NOT OPTIONAL, you have to explicitly set it.
.PP
You can specify additional flags to add to the command, for example if you want
to export an electron app, you could add the "\-\-foreground" flag to the command:

distrobox\-export \fB\-\-app\fR atom \fB\-\-extra\-flags\fR "\-\-foreground"
distrobox\-export \fB\-\-bin\fR \fI\,/usr/bin/vim\/\fP \fB\-\-export\-path\fR ~/.local/bin \fB\-\-extra\-flags\fR "\-p"
distrobox\-export \fB\-\-service\fR syncthing \fB\-\-extra\-flags\fR "\-allow\-newer\-config"
.PP
This works for services, binaries, and apps.
Extra flags are only used then the exported app, binary, or service is used from
the host, using them inside the container will not include them.
.PP
The option "\-\-delete" will un\-export an app, binary, or service.
distrobox\-export \fB\-\-app\fR atom \fB\-\-delete\fR
distrobox\-export \fB\-\-bin\fR \fI\,/usr/bin/vim\/\fP \fB\-\-export\-path\fR ~/.local/bin \fB\-\-delete\fR
distrobox\-export \fB\-\-service\fR syncthing \fB\-\-delete\fR
distrobox\-export \fB\-\-service\fR nginx \fB\-\-delete\fR
.PP
The option "\-\-sudo" will launch the exported item as root inside the distrobox.
.PP
Note you can use \fB\-\-app\fR OR \fB\-\-bin\fR OR \fB\-\-service\fR but not together.
distrobox\-export \fB\-\-service\fR nginx \fB\-\-sudo\fR
.PP
Usage:
distrobox\-export \fB\-\-app\fR mpv [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
distrobox\-export \fB\-\-service\fR syncthing [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
distrobox\-export \fB\-\-bin\fR \fI\,/path/to/bin\/\fP \fB\-\-export\-path\fR ~/.local/bin [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
.SH OPTIONS
.TP
\fB\-\-app\fR/\-a:
name of the application to export
.TP
\fB\-\-bin\fR/\-b:
absolute path of the binary to export
.TP
\fB\-\-service\fR/\-s:
name of the service to export
.TP
\fB\-\-delete\fR/\-d:
delete exported application or service
.TP
\fB\-\-export\-path\fR/\-ep:
path where to export the binary
.TP
\fB\-\-extra\-flags\fR/\-ef:
extra flags to add to the command
.TP
\fB\-\-sudo\fR/\-S:
specify if the exported item should be ran as sudo
.TP
\fB\-\-help\fR/\-h:
show this message
.TP
\fB\-\-verbose\fR/\-v:
show more verbosity
.TP
\fB\-\-version\fR/\-V:
show version
.SH "SEE ALSO"
GitHub repository is located at https://github.com/89luca89/distrobox
