.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-EXPORT\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-export\.1\fR
.P
# Application and service exporting
.P
distrobox\-export takes care of exporting an app a binary or a service from the container to the host\.
.P
The exported app will be easily available in your normal launcher and it will automatically be launched from the container it is exported from\.
.P
The exported services will be available in the host\'s user\'s systemd session, so
.IP "" 4
.nf
systemctl \-\-user status exported_service_name
.fi
.IP "" 0
.P
will show the status of the service exported\.
.P
The exported binaries will be exported in the "\-\-export\-path" of choice as a wrapper script that acts naturally both on the host and in the container\. Note that "\-\-export\-path" is NOT OPTIONAL, you have to explicitly set it\.
.P
You can specify additional flags to add to the command, for example if you want to export an electron app, you could add the "\-\-foreground" flag to the command:
.IP "" 4
.nf
distrobox\-export \-\-app atom \-\-extra\-flags "\-\-foreground"
distrobox\-export \-\-bin /usr/bin/vim \-\-export\-path ~/\.local/bin \-\-extra\-flags "\-p"
distrobox\-export \-\-service syncthing \-\-extra\-flags "\-allow\-newer\-config"
.fi
.IP "" 0
.P
This works for services, binaries, and apps\. Extra flags are only used then the exported app, binary, or service is used from the host, using them inside the container will not include them\.
.P
The option "\-\-delete" will un\-export an app, binary, or service\.
.IP "" 4
.nf
distrobox\-export \-\-app atom \-\-delete
distrobox\-export \-\-bin /usr/bin/vim \-\-export\-path ~/\.local/bin \-\-delete
distrobox\-export \-\-service syncthing \-\-delete
distrobox\-export \-\-service nginx \-\-delete
.fi
.IP "" 0
.P
The option "\-\-sudo" will launch the exported item as root inside the distrobox\.
.P
Note you can use \-\-app OR \-\-bin OR \-\-service but not together\.
.IP "" 4
.nf
distrobox\-export \-\-service nginx \-\-sudo
.fi
.IP "" 0
.P
Usage:
.IP "" 4
.nf
distrobox\-export \-\-app mpv [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
distrobox\-export \-\-service syncthing [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
distrobox\-export \-\-bin /path/to/bin \-\-export\-path ~/\.local/bin [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-app/\-a:		name of the application to export
\-\-bin/\-b:		absolute path of the binary to export
\-\-service/\-s:		name of the service to export
\-\-delete/\-d:		delete exported application or service
\-\-export\-label/\-el:	label to add to exported application name\.
			Defaults to (on \e$container_name)
\-\-export\-path/\-ep:	path where to export the binary
\-\-extra\-flags/\-ef:	extra flags to add to the command
\-\-sudo/\-S:		specify if the exported item should be ran as sudo
\-\-help/\-h:		show this message
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0
.P
You may want to install graphical applications or user services in your distrobox\. Using \fBdistrobox\-export\fR from \fBinside\fR the container will let you use them from the host itself\.
.P
App export example:
.IP "" 4
.nf
distrobox\-export \-\-app abiword
.fi
.IP "" 0
.P
This tool will simply copy the original \fB\.desktop\fR files along with needed icons, add the prefix \fB/usr/local/bin/distrobox\-enter \-n distrobox_name \-e \|\.\|\.\|\.\fR to the commands to run, and save them in your home to be used directly from the host as a normal app\.
.P
Service export example:
.IP "" 4
.nf
distrobox\-export \-\-service syncthing \-\-extra\-flags "\-\-allow\-newer\-config"
distrobox\-export \-\-service nginx \-\-sudo
.fi
.IP "" 0
.P
For services, it will similarly export the systemd unit inside the container to a \fBsystemctl \-\-user\fR service, prefixing the various \fBExecStart ExecStartPre ExecStartPost ExecReload ExecStop ExecStopPost\fR with the \fBdistrobox\-enter\fR command prefix\.
.P
Binary export example:
.IP "" 4
.nf
distrobox\-export \-\-bin /usr/bin/code \-\-extra\-flags "\-\-foreground" \-\-export\-path $HOME/\.local/bin
.fi
.IP "" 0
.P
In the case of exporting binaries, you will have to specify \fBwhere\fR to export it (\fB\-\-export\-path\fR) and the tool will create a little wrapper script that will \fBdistrobox\-enter \-e\fR from the host, the desired binary\. This can be handy with the use of \fBdirenv\fR to have different versions of the same binary based on your \fBenv\fR or project\.
.P
.P
.P
NOTE: some electron apps such as vscode and atom need additional flags to work from inside the container, use the \fB\-\-extra\-flags\fR option to provide a series of flags, for example:
.P
\fBdistrobox\-export \-\-app atom \-\-extra\-flags "\-\-foreground"\fR
