.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-COMPATIBILITY\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-compatibility\.1\fR \- Compatibility
.P
This project \fBdoes not need a dedicated image\fR\. It can use any OCI images from docker\-hub, quay\.io, or any registry of your choice\.
.P
Granted, they may not be as featureful as expected (some of them do not even have \fBwhich\fR, \fBmount\fR, \fBless\fR or \fBvi\fR) but that\'s all doable in the container itself after bootstrapping it\.
.P
The main concern is having basic Linux utilities (\fBmount\fR), basic user management utilities (\fBusermod, passwd\fR), and \fBsudo\fR correctly set\.
.SH "Supported container managers"
\fBdistrobox\fR can run on either \fBpodman\fR or \fBdocker\fR
.P
It depends either on \fBpodman\fR configured in \fBrootless mode\fR or on \fBdocker\fR configured without sudo (follow THIS instructions \fIhttps://docs\.docker\.com/engine/install/linux\-postinstall/\fR)
.IP "\[ci]" 4
Minimum podman version: \fB2\.1\.0\fR
.IP "\[ci]" 4
Minimum docker version: \fB18\.06\.1\fR
.IP "" 0
.P
Follow the official installation guide here:
.IP "\[ci]" 4
\fIhttps://podman\.io/getting\-started/installation\fR
.IP "\[ci]" 4
\fIhttps://docs\.docker\.com/engine/install\fR
.IP "\[ci]" 4
\fIhttps://docs\.docker\.com/engine/install/linux\-postinstall/\fR
.IP "" 0
.SH "Containers Distros"
Distrobox guests tested successfully with the following container images:
.TS
allbox;
l l l.
Distro	Version	Images
AlmaLinux	8	docker\.io/library/almalinux:8
AlmaLinux (UBI)	8	docker\.io/almalinux/8\-base
.br
docker\.io/almalinux/8\-init
Alpine Linux	3\.14
.br
3\.15	docker\.io/library/alpine:latest
AmazonLinux	2	docker\.io/library/amazonlinux:2\.0\.20211005\.0
AmazonLinux	2022	public\.ecr\.aws/amazonlinux/amazonlinux:2022
Archlinux	\~	docker\.io/library/archlinux:latest
ClearLinux	\~	docker\.io/library/clearlinux:latest
.br
docker\.io/library/clearlinux:base
CentOS	7	quay\.io/centos/centos:7
CentOS Stream	8
.br
9	quay\.io/centos/centos:stream8
.br
quay\.io/centos/centos:stream9
RedHat (UBI)	7
.br
8	registry\.access\.redhat\.com/ubi7/ubi
.br
registry\.access\.redhat\.com/ubi7/ubi\-init
.br
registry\.access\.redhat\.com/ubi8/ubi
.br
registry\.access\.redhat\.com/ubi8/ubi\-init
Debian	7
.br
8
.br
9
.br
10
.br
11	docker\.io/debian/eol:wheezy
.br
docker\.io/library/debian:8
.br
docker\.io/library/debian:9
.br
docker\.io/library/debian:10
.br
docker\.io/library/debian:stable
.br
docker\.io/library/debian:stable\-backports
Debian	Testing	docker\.io/library/debian:testing
.br
docker\.io/library/debian:testing\-backports
Debian	Unstable	docker\.io/library/debian:unstable
Neurodebian	nd100	docker\.io/library/neurodebian:nd100
Fedora	34
.br
35
.br
36
.br
37
.br
Rawhide	registry\.fedoraproject\.org/fedora\-toolbox:34
.br
docker\.io/library/fedora:34
.br
registry\.fedoraproject\.org/fedora\-toolbox:35
.br
docker\.io/library/fedora:35
.br
docker\.io/library/fedora:36
.br
registry\.fedoraproject\.org/fedora:37
.br
docker\.io/library/fedora:rawhide
Mageia	8	docker\.io/library/mageia
Opensuse	Leap	registry\.opensuse\.org/opensuse/leap:latest
Opensuse	Tumbleweed	registry\.opensuse\.org/opensuse/tumbleweed:latest
.br
registry\.opensuse\.org/opensuse/toolbox:latest
Oracle Linux	7
.br
8	container\-registry\.oracle\.com/os/oraclelinux:7
.br
container\-registry\.oracle\.com/os/oraclelinux:8
Rocky Linux	8	docker\.io/rockylinux/rockylinux:8
Scientific Linux	7	docker\.io/library/sl:7
Slackware	14\.2	docker\.io/vbatts/slackware:14\.2
Ubuntu	14\.04
.br
16\.04
.br
18\.04
.br
20\.04
.br
21\.10
.br
22\.04	docker\.io/library/ubuntu:14\.04
.br
docker\.io/library/ubuntu:16\.04
.br
docker\.io/library/ubuntu:18\.04
.br
docker\.io/library/ubuntu:20\.04
.br
docker\.io/library/ubuntu:21\.10
.br
docker\.io/library/ubuntu:22\.04
Kali Linux	rolling	docker\.io/kalilinux/kali\-rolling:latest
Void Linux	\~	ghcr\.io/void\-linux/void\-linux:latest\-full\-x86_64
.br
ghcr\.io/void\-linux/void\-linux:latest\-full\-x86_64\-musl
Gentoo Linux	rolling	You will have to Build your own \fIdistrobox_gentoo\.md\fR to have a complete Gentoo docker image
.TE
.P
Note however that if you use a non\-toolbox preconfigured image (e\.g\. images pre\-baked to work with \fIhttps://github\.com/containers/toolbox),\fR the \fBfirst\fR \fBdistrobox\-enter\fR you\'ll perform can take a while as it will download and install the missing dependencies\.
.P
A small time tax to pay for the ability to use any type of image\. This will \fBnot\fR occur after the first time, \fBsubsequent enters will be much faster\.\fR
.P
NixOS is not a supported container distro, and there are currently no plans to bring support to it\. If you are looking for unprivlaged NixOS environments, we suggest you look into nix\-shell \fIhttps://nixos\.org/manual/nix/unstable/command\-ref/nix\-shell\.html\fR\.
.SS "New Distro support"
If your distro of choice is not on the list, open an issue requesting support for it, we can work together to check if it is possible to add support for it\.
.P
Or just try using it anyway, if it works, open an issue and it will be added to the list!
.SS "Older distributions"
For older distributions like CentOS 5, CentOS 6, Debian 6, Ubuntu 12\.04, compatibility is not assured\.
.P
Their \fBlibc\fR version is incompatible with kernel releases after \fB>=4\.11\fR\. A work around this is to use the \fBvsyscall=emulate\fR flag in the bootloader of the host\.
.P
Keep also in mind that mirrors could be down for such old releases, so you will need to build a custom distrobox image to ensure basic dependencies are met \fI\./distrobox_custom\.md\fR\.
.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-CREATE\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-create\.1\fR
.P
# Create the distrobox
.P
distrobox\-create takes care of creating the container with input name and image\. The created container will be tightly integrated with the host, allowing sharing of the HOME directory of the user, external storage, external usb devices and graphical apps (X11/Wayland), and audio\.
.P
Usage:
.IP "" 4
.nf
distrobox\-create \-\-image registry\.fedoraproject\.org/fedora\-toolbox:35 \-\-name fedora\-toolbox\-35
distrobox\-create \-\-clone fedora\-toolbox\-35 \-\-name fedora\-toolbox\-35\-copy
distrobox\-create \-\-image alpine my\-alpine\-container
distrobox create \-\-image fedora:35 \-\-name test \-\-volume /opt/my\-dir:/usr/local/my\-dir:rw \-\-additional\-flags "\-\-pids\-limit \-1"
distrobox create \-\-image fedora:35 \-\-name test \-\-additional\-flags "\-\-env MY_VAR\-value"
distrobox create \-\-image alpine:latest \-\-name test \-\-init\-hooks "touch /var/tmp/test1 && touch /var/tmp/test2"
distrobox create \-i docker\.io/almalinux/8\-init \-\-init \-\-name test
.fi
.IP "" 0
.P
You can also use environment variables to specify container name and image
.IP "" 4
.nf
DBX_NON_INTERACTIVE=1 DBX_CONTAINER_NAME=test\-alpine DBX_CONTAINER_IMAGE=alpine distrobox\-create
.fi
.IP "" 0
.P
Supported environment variables:
.IP "" 4
.nf
DBX_NON_INTERACTIVE
DBX_CONTAINER_NAME
DBX_CONTAINER_IMAGE
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-image/\-i:		image to use for the container	default: registry\.fedoraproject\.org/fedora\-toolbox:35
\-\-name/\-n:		name for the distrobox		default: fedora\-toolbox\-35
\-\-yes/\-Y:	non\-interactive, pull images without asking
\-\-clone/\-c:		name of the distrobox container to use as base for a new container
			this will be useful to either rename an existing distrobox or have multiple copies
			of the same environment\.
\-\-home/\-H		select a custom HOME directory for the container\. Useful to avoid host\'s home littering with temp files\.
\-\-volume		additional volumes to add to the container
\-\-additional\-flags/\-a:	additional flags to pass to the container manager command
\-\-init\-hooks		additional commands to execute during container initialization
\-\-init/\-I		use init system (like systemd) inside the container\.
			this will make host\'s processes not visible from within the container\.
\-\-help/\-h:		show this message
\-\-dry\-run/\-d:		only print the container manager command generated
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0
.P
Compatibility:
.IP "" 4
.nf
for a list of compatible images and container managers, please consult the man page:
	man distrobox
	man distrobox\-compatibility
or consult the documentation page on: https://github\.com/89luca89/distrobox/blob/main/docs/compatibility\.md#containers\-distros
.fi
.IP "" 0
.P
The \fB\-\-additional\-flags\fR or \fB\-a\fR is useful to modify defaults in the container creations\. For example:
.IP "" 4
.nf
distrobox create \-i docker\.io/library/archlinux \-n dev\-arch

podman container inspect dev\-arch | jq \'\.[0]\.HostConfig\.PidsLimit\'
2048

distrobox rm \-f dev\-arch
distrobox create \-i docker\.io/library/archlinux \-n dev\-arch \-\-volume $CBL_TC:/tc \-\-additional\-flags "\-\-pids\-limit \-1"

podman container inspect dev\-arch | jq \'\.[0]\.HostConfig,\.PidsLimit\'
0
.fi
.IP "" 0
.P
Additional volumes can be specified using the \fB\-\-volume\fR flag\. This flag follows the same standard as \fBdocker\fR and \fBpodman\fR to specify the mount point so \fB\-\-volume SOURCE_PATH:DEST_PATH:MODE\fR\.
.IP "" 4
.nf
distrobox create \-\-image docker\.io/library/archlinux \-\-name dev\-arch \-\-volume /usr/share/:/var/test:ro
.fi
.IP "" 0
.P
During container creation, it is possible to specify (using the additional\-flags) some environment variables that will persist in the container and be independent from your environment:
.IP "" 4
.nf
distrobox create \-\-image fedora:35 \-\-name test \-\-additional\-flags "\-\-env MY_VAR\-value"
.fi
.IP "" 0
.P
The \fB\-\-init\-hooks\fR is useful to add commands to the entrypoint (init) of the container\. This could be useful to create containers with a set of programs already installed, add users, groups\.
.IP "" 4
.nf
distrobox create  \-\-image fedora:35 \-\-name test \-\-init\-hooks "dnf groupinstall \-y \e"C Development Tools and Libraries\e""
.fi
.IP "" 0
.P
The \fB\-\-init\fR is useful to create a container that will use its own separate init system within\. For example using:
.IP "" 4
.nf
distrobox create \-i docker\.io/almalinux/8\-init \-\-init\-hooks "dnf install \-y openssh\-server" \-\-init \-\-name test
.fi
.IP "" 0
.P
Inside the container we will be able to use normal systemd units:
.IP "" 4
.nf
~$ distrobox enter test
user@test:~$ sudo systemctl enable \-\-now sshd
user@test:~$ sudo systemctl status sshd
	● sshd\.service \- OpenSSH server daemon
	   Loaded: loaded (/usr/lib/systemd/system/sshd\.service; enabled; vendor preset: enabled)
	   Active: active (running) since Fri 2022\-01\-28 22:54:50 CET; 17s ago
		 Docs: man:sshd(8)
			   man:sshd_config(5)
	 Main PID: 291 (sshd)
.fi
.IP "" 0
.P
Note that enabling \fB\-\-init\fR \fBwill disable host\'s process integration\fR\. From within the container you will not be able to see and manage host\'s processes\. This is needed because \fB/sbin/init\fR must be pid 1\.
.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-ENTER\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-enter\.1\fR
.P
# Enter the distrobox
.P
distrobox\-enter takes care of entering the container with the name specified\. Default command executed is your SHELL, but you can specify different shells or entire commands to execute\. If using it inside a script, an application, or a service, you can specify the \-\-headless mode to disable tty and interactivity\.
.P
Usage:
.IP "" 4
.nf
distrobox\-enter \-\-name fedora\-toolbox\-35 \-\- bash \-l
distrobox\-enter my\-alpine\-container \-\- sh \-l
distrobox\-enter \-\-additional\-flags "\-\-preserve\-fds" \-\-name test \-\- bash \-l
distrobox\-enter \-\-additional\-flags "\-\-env MY_VAR=value" \-\-name test \-\- bash \-l
MY_VAR=value distrobox\-enter \-\-additional\-flags "\-\-preserve\-fds" \-\-name test \-\- bash \-l
.fi
.IP "" 0
.P
Supported environment variables:
.IP "" 4
.nf
DBX_CONTAINER_NAME
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-name/\-n:		name for the distrobox						default: fedora\-toolbox\-35
\-\-/\-e:			end arguments execute the rest as command to execute at login	default: bash \-l
\-\-no\-tty/\-T:		do not instantiate a tty
\-\-additional\-flags/\-a:	additional flags to pass to the container manager command
\-\-help/\-h:		show this message
\-\-dry\-run/\-d:		only print the container manager command generated
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0
.P
This is used to enter the distrobox itself\. Personally, I just create multiple profiles in my \fBgnome\-terminal\fR to have multiple distros accessible\.
.P
The \fB\-\-additional\-flags\fR or \fB\-a\fR is useful to modify default command when executing in the container\. For example:
.IP "" 4
.nf
distrobox enter \-n dev\-arch \-\-additional\-flags "\-\-env my_var=test" \-\- printenv &| grep my_var
my_var=test
.fi
.IP "" 0
.P
This is possible also using normal env variables:
.IP "" 4
.nf
my_var=test distrobox enter \-n dev\-arch \-\-additional\-flags \-\- printenv &| grep my_var
my_var=test
.fi
.IP "" 0

.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-EXPORT\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-export\.1\fR
.P
# Application and service exporting
.P
distrobox\-export takes care of exporting an app a binary or a service from the container to the host\.
.P
The exported app will be easily available in your normal launcher and it will automatically be launched from the container it is exported from\.
.P
The exported services will be available in the host\'s user\'s systemd session, so
.IP "" 4
.nf
systemctl \-\-user status exported_service_name
.fi
.IP "" 0
.P
will show the status of the service exported\.
.P
The exported binaries will be exported in the "\-\-export\-path" of choice as a wrapper script that acts naturally both on the host and in the container\. Note that "\-\-export\-path" is NOT OPTIONAL, you have to explicitly set it\.
.P
You can specify additional flags to add to the command, for example if you want to export an electron app, you could add the "\-\-foreground" flag to the command:
.IP "" 4
.nf
distrobox\-export \-\-app atom \-\-extra\-flags "\-\-foreground"
distrobox\-export \-\-bin /usr/bin/vim \-\-export\-path ~/\.local/bin \-\-extra\-flags "\-p"
distrobox\-export \-\-service syncthing \-\-extra\-flags "\-allow\-newer\-config"
.fi
.IP "" 0
.P
This works for services, binaries, and apps\. Extra flags are only used then the exported app, binary, or service is used from the host, using them inside the container will not include them\.
.P
The option "\-\-delete" will un\-export an app, binary, or service\.
.IP "" 4
.nf
distrobox\-export \-\-app atom \-\-delete
distrobox\-export \-\-bin /usr/bin/vim \-\-export\-path ~/\.local/bin \-\-delete
distrobox\-export \-\-service syncthing \-\-delete
distrobox\-export \-\-service nginx \-\-delete
.fi
.IP "" 0
.P
The option "\-\-sudo" will launch the exported item as root inside the distrobox\.
.P
Note you can use \-\-app OR \-\-bin OR \-\-service but not together\.
.IP "" 4
.nf
distrobox\-export \-\-service nginx \-\-sudo
.fi
.IP "" 0
.P
Usage:
.IP "" 4
.nf
distrobox\-export \-\-app mpv [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
distrobox\-export \-\-service syncthing [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
distrobox\-export \-\-bin /path/to/bin \-\-export\-path ~/\.local/bin [\-\-extra\-flags "flags"] [\-\-delete] [\-\-sudo]
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-app/\-a:		name of the application to export
\-\-bin/\-b:		absolute path of the binary to export
\-\-service/\-s:		name of the service to export
\-\-delete/\-d:		delete exported application or service
\-\-export\-label/\-el:	label to add to exported application name\.
			Defaults to (on \e$container_name)
\-\-export\-path/\-ep:	path where to export the binary
\-\-extra\-flags/\-ef:	extra flags to add to the command
\-\-sudo/\-S:		specify if the exported item should be ran as sudo
\-\-help/\-h:		show this message
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0
.P
You may want to install graphical applications or user services in your distrobox\. Using \fBdistrobox\-export\fR from \fBinside\fR the container will let you use them from the host itself\.
.P
App export example:
.IP "" 4
.nf
distrobox\-export \-\-app abiword
.fi
.IP "" 0
.P
This tool will simply copy the original \fB\.desktop\fR files along with needed icons, add the prefix \fB/usr/local/bin/distrobox\-enter \-n distrobox_name \-e \|\.\|\.\|\.\fR to the commands to run, and save them in your home to be used directly from the host as a normal app\.
.P
Service export example:
.IP "" 4
.nf
distrobox\-export \-\-service syncthing \-\-extra\-flags "\-\-allow\-newer\-config"
distrobox\-export \-\-service nginx \-\-sudo
.fi
.IP "" 0
.P
For services, it will similarly export the systemd unit inside the container to a \fBsystemctl \-\-user\fR service, prefixing the various \fBExecStart ExecStartPre ExecStartPost ExecReload ExecStop ExecStopPost\fR with the \fBdistrobox\-enter\fR command prefix\.
.P
Binary export example:
.IP "" 4
.nf
distrobox\-export \-\-bin /usr/bin/code \-\-extra\-flags "\-\-foreground" \-\-export\-path $HOME/\.local/bin
.fi
.IP "" 0
.P
In the case of exporting binaries, you will have to specify \fBwhere\fR to export it (\fB\-\-export\-path\fR) and the tool will create a little wrapper script that will \fBdistrobox\-enter \-e\fR from the host, the desired binary\. This can be handy with the use of \fBdirenv\fR to have different versions of the same binary based on your \fBenv\fR or project\.
.P
.P
.P
NOTE: some electron apps such as vscode and atom need additional flags to work from inside the container, use the \fB\-\-extra\-flags\fR option to provide a series of flags, for example:
.P
\fBdistrobox\-export \-\-app atom \-\-extra\-flags "\-\-foreground"\fR
.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-INIT\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-init\.1\fR
.P
# Init the distrobox (not to be launched manually)
.P
distrobox\-init is the entrypoint of a created distrobox\. Note that this HAS to run from inside a distrobox, will not work if you run it from your host\.
.P
This is not intended to be used manually, but instead used by distrobox\-enter to set up the container\'s entrypoint\.
.P
distrobox\-init will take care of installing missing dependencies (eg\. sudo), set up the user and groups, mount directories from the host to ensure the tight integration\.
.P
Usage:
.IP "" 4
.nf
distrobox\-init \-\-name test\-user \-\-user 1000 \-\-group 1000 \-\-home /home/test\-user
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-name/\-n:		user name
\-\-user/\-u:		uid of the user
\-\-group/\-g:		gid of the user
\-\-home/\-d:		path/to/home of the user
\-\-help/\-h:		show this message
\-\-init/\-I:		whether to use or not init
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
\-\-:			end arguments execute the rest as command to execute during init
.fi
.IP "" 0
.P
This is used as entrypoint for the created container, it will take care of creating the users, setting up sudo, mountpoints, and exports\.
.P
\fBYou should not have to launch this manually\fR, this is used by \fBdistrobox create\fR to set up container\'s entrypoint\.
.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-LIST\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-list\.1\fR
.P
# List containers
.P
distrobox\-list lists available distroboxes\. It detects them and lists them separately from the rest of normal podman or docker containers\.
.P
Usage:
.IP "" 4
.nf
distrobox\-list
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-help/\-h:		show this message
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0
.P

.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-RM\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-rm\.1\fR
.P
# Remove containers
.P
distrobox\-rm delete one of the available distroboxes\.
.P
Usage:
.IP "" 4
.nf
distrobox\-rm \-\-name container\-name [\-\-force]
distrobox\-rm container\-name [\-f]
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-name/\-n:		name for the distrobox
\-\-force/\-f:		force deletion
\-\-help/\-h:		show this message
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0

.\" generated with Ronn-NG/v0.9.1
.\" http://github.com/apjanke/ronn-ng/tree/0.9.1
.TH "DISTROBOX\-STOP\.1" "" "April 2022" "Distrobox" "Distrobox"
.SH "NAME"
\fBdistrobox\-stop\.1\fR
.P
# Stop containers
.P
distrobox\-rm delete one of the available distroboxes\.
.P
Usage:
.IP "" 4
.nf
distrobox\-rm \-\-name container\-name
distrobox\-rm container\-name
.fi
.IP "" 0
.P
Options:
.IP "" 4
.nf
\-\-name/\-n:		name for the distrobox
\-\-yes/\-Y:		non\-interactive, stop without asking
\-\-help/\-h:		show this message
\-\-verbose/\-v:		show more verbosity
\-\-version/\-V:		show version
.fi
.IP "" 0

