#!/bin/sh
# SPDX-License-Identifier: GPL-3.0-only
#
# This file is part of the distrobox project: https://github.com/89luca89/distrobox
#
# Copyright (C) 2021 distrobox contributors
#
# distrobox is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 3
# as published by the Free Software Foundation.
#
# distrobox is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with distrobox; if not, see <http://www.gnu.org/licenses/>.

# POSIX

echo "This script is deprecated and unsupported"
echo "head over to:"
echo ""
echo "https://github.com/89luca89/distrobox/blob/main/docs/posts/install_podman_static.md"
echo "or"
echo "https://github.com/89luca89/distrobox/blob/main/docs/posts/install_lilipod_static.md"
echo ""
echo "for updated instructions on how to install podman-launcher"

exit 1
